# Generated by Django 5.0.6 on 2024-12-08 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='profesor'),
        ),
    ]
