# Generated by Django 5.0.6 on 2024-12-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_profesor_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='rol',
            field=models.CharField(default='profesor', editable=False, max_length=50),
        ),
    ]
