# Generated by Django 5.0.6 on 2024-12-09 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_estudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='rol',
            field=models.CharField(default='estudiante', editable=False, max_length=50),
        ),
    ]
